require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "gems/**/*"
    - "db/schema.rb"

Layout/LineLength:
  Exclude:
    - "config/initializers/simple_form_bootstrap.rb"
    - "config/initializers/simple_form.rb"

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - "config/initializers/simple_form_bootstrap.rb"

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false
