require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "gems/**/*"
    - "db/schema.rb"

Layout/LineLength:
  Exclude:
    - "config/initializers/simple_form_bootstrap.rb"
    - "config/initializers/simple_form.rb"

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "config/initializers/simple_form_bootstrap.rb"
    - "db/seeds.rb"

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  CountComments: false
  Max: 20
  Exclude:
    - "db/seeds.rb"

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
